# name: Python Flask CI/CD

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.9'
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#     - name: Run tests
#       run: |
#         python -m unittest discover tests

#   deploy-staging:
#     needs: test
#     runs-on: ubuntu-latest
#     if: github.event_name == 'push' && github.ref == 'refs/heads/master'
#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Install SSH Key
#       uses: shimataro/ssh-key-action@v2
#       with:
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
#     - name: Deploy to Staging
#       run: |
#         ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} << EOF
#          cd /home/ubuntu/python
#          git init
#          git remote add origin https://github.com/Graceful-star/Seans-Python3-Flask-Rest-Boilerplate.git
#          git fetch origin master
#          git reset --hard origin/master
#          python3 -m venv /home/ubuntu/your-app-venv
#          source /home/ubuntu/your-app-venv/bin/activate
#          /home/ubuntu/your-app-venv/bin/pip install -r requirements.txt
#          sudo systemctl restart your-flask-app.service
         


name: Python Flask CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m unittest discover tests

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    
    - name: Deploy to Staging
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        ssh $USERNAME@$HOST << EOF
          # Update system
          sudo apt update && sudo apt upgrade -y

          # Ensure required packages are installed
          sudo apt install -y python3-venv

          # Set up application directory
          mkdir -p ~/flask-app
          cd ~/flask-app

          # Set up Git repository
          git init
          git remote add origin https://github.com/${{ github.repository }}.git
          git fetch origin master
          git reset --hard origin/master

          # Set up Python virtual environment
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

          # Create systemd service file
          sudo tee /etc/systemd/system/flask-app.service > /dev/null << EOT
          [Unit]
          Description=Flask App
          After=network.target

          [Service]
          User=$USERNAME
          WorkingDirectory=/home/$USERNAME/flask-app
          ExecStart=/home/$USERNAME/flask-app/venv/bin/python app.py
          Restart=always

          [Install]
          WantedBy=multi-user.target
          EOT

          # Reload systemd, enable and restart the service
          sudo systemctl daemon-reload
          sudo systemctl enable flask-app.service
          sudo systemctl restart flask-app.service

          # Output service status for logging
          sudo systemctl status flask-app.service
        
